### ISSUE TITLE
can i specify multiple repos in one step?

### ISSUE THREAD

**Issue by 0xbe1** [jaxxstorm/action-install-gh-release#29]
instead of

```
steps:
      - name: install substreams cli
        uses: jaxxstorm/action-install-gh-release@v1.7.1
        with:
          repo: streamingfast/substreams
          cache: enable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: install buf
        uses: jaxxstorm/action-install-gh-release@v1.7.1
        with:
          repo: bufbuild/buf
          cache: enable
```

can I do the below instead?

```
      - name: install substreams cli
        uses: jaxxstorm/action-install-gh-release@v1.7.1
        with:
          - repo: streamingfast/substreams
            cache: enable
          - repo: bufbuild/buf
            cache: enable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

thanks!
