### ISSUE TITLE
Unexpected input(s) 'platform', 'arch', valid inputs are ['repo', 'tag']

### ISSUE THREAD

**Issue by edgeb1-roche** [jaxxstorm/action-install-gh-release#35]
The ['platform', 'arch'] are not recognized as valid parameters despite being shown in the README.

This workflow snippet where I picked a public repo to use as a test case:
```
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Download repo-copier binary
      uses: jaxxstorm/action-install-gh-release@v1.5.0
      with: # Grab a specific platform and/or architecture
        repo: jaxxstorm/connecti
        tag: v0.0.3
        platform: linux              <- this
        arch: x86-64               <- and this
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

log:
```
Warning: Unexpected input(s) 'platform', 'arch', valid inputs are ['repo', 'tag']
##[debug]Loading env
Run jaxxstorm/action-install-gh-release@v1.5.0
  with:
    repo: jaxxstorm/connecti
    tag: v0.0.3
    platform: linux
    arch: x86-64
  env:
    GITHUB_TOKEN: ***
```

Ref: https://github.com/jaxxstorm/action-install-gh-release#grab-a-specific-platform-andor-architecture

From docs:
```
name: my_action

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Github token scoped to action

jobs:
  my_job:
    steps:
      - name: Install tfsec
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with: # Grab a specific platform and/or architecture
          repo: aquasecurity/tfsec
          platform: linux
          arch: x86-64
```
