### ISSUE TITLE
binaries-location not working as expected

### ISSUE THREAD

**Issue by danhngo-lx** [jaxxstorm/action-install-gh-release#64]
I use this to install promtool:
```
      - name: Install promtool
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: prometheus/prometheus
          tag: 'v2.37.9'
          platform: linux
          arch: amd64
          cache: enable
          binaries-location: prometheus-2.37.9.linux-amd64
```

However when using promtool, the command is not found. I tried to echo $PATH and could see:
```
/opt/hostedtoolcache/prometheus/prometheus/v2.37.9/linux-amd64:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/runner/.local/bin
```

I think the path for prometheus should be `/opt/hostedtoolcache/prometheus/prometheus/v2.37.9/linux-amd64/prometheus-2.37.9.linux-amd64` instead of `/opt/hostedtoolcache/prometheus/prometheus/v2.37.9/linux-amd64`? 🤔 

I'm using github runner self-hosted by the way.
