### ISSUE TITLE
Feature request:  Determine platform and architecture from the github runner.

### ISSUE THREAD

**Issue by JamesParrott** [jaxxstorm/action-install-gh-release#71]
This is a Github Action.  Even if there actually is an application, in which a release is preferred for a platform or architecture different to the one the code itself is running on, that should not be the default.

**Comment by JamesParrott** [comment]
I should've read the docs sorry.  The code tries to do this already.  

It's even case insensitive

https://github.com/jaxxstorm/action-install-gh-release/blob/2fba7e5bd9dcf38d6ab500fa0f8c0b0e46884336/src/main.ts#L179


This project's fantastic - well done guys.  I needed to disable extension matching - this eventually worked for me:
```
      - name: Install Hadolint
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with: 
          repo: hadolint/hadolint
          tag: 'v2.12.0'
          platform: 'linux'
          arch: 'x86_64'
          extension-matching: disable
          rename-to: hadolint
          chmod: 0755
```
