### ISSUE TITLE
Allow to specify artifact full filename

### ISSUE THREAD

**Issue by genert** [jaxxstorm/action-install-gh-release#84]
Unfortunately this action does not allow currently to specify exact filename when there are multiple different binaries in the release.

Example - https://github.com/bazel-contrib/target-determinator/releases

It publishes 2 binaries: driver and target-determinator. Currently with the following configuration, it downloads the driver although I want the latter.

```
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: bazel-contrib/target-determinator
          tag: v0.26.0
          extension-matching: disable
          rename-to: target-determinator
          chmod: 0755
```
