### ISSUE TITLE
Handle releases nested within single directories

### ISSUE THREAD

**Issue by orf** [jaxxstorm/action-install-gh-release#88]
Hey, thank you for this awesome action ❤️.

I was trying to use it with Hyperfine:

```yaml
      - name: install hyperfine
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: sharkdp/hyperfine
```

However this fails, because the extracted release file contains a single directory called `hyperfine-v1.18.0-x86_64-unknown-linux-gnu/`

As a workaround, you can do:

```yaml
      - name: install hyperfine
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: sharkdp/hyperfine
          tag: v1.18.0
          binaries-location: hyperfine-v1.18.0-x86_64-unknown-linux-gnu
```

However this isn't ideal. It would be awesome if the action could detect if the release file has a single extracted directory, and use that to find the binaries automatically?

**Comment by jaxxstorm** [comment]
I don't have any plans to add logic for the myriad ways that directories can be placed in an archive, I think binaries-location is a fine way of handling this. Closing

**Comment by tmke8** [comment]
I have the same problem with https://github.com/WebAssembly/binaryen . You're right that `binaries-location` is a fine way of handling it, but the issue is that the path name depends on the tag. A solution might be to allow some kind of tag placeholder in the `binaries-location` path.

This is what I currently do:

```yaml
      - name: "Install wasm-opt"
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: WebAssembly/binaryen
          tag: version_128
          binaries-location: binaryen-version_128/bin
          chmod: 0755
```

But I would prefer not pinning the tag.
